fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: false
#    text: 这是一条 Slogan
#    typeSpeed: 70 # 打印速度
#    cursorChar: "_" # 游标字符
#    loop: false # 是否循环播放效果
navbar:
  blog_title: Aiden
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archives', link: '/archives/', icon: 'iconfont icon-archive-fill', name: '归档' }
    - { key: 'categories', link: '/categories/', icon: 'iconfont icon-category-fill', name: '分类' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '联系我' }

index:
  slogan:
    enable: true
    text: Aiden
  # 开关自动摘要（默认开启）
  auto_excerpt:
    enable: true
  # 文章跳转方式
  post_url_target: _self
  post_sticky:
    enable: true
    icon: 'iconfont icon-top'
post:
  meta:
    author:  # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: false
    date:  # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: true
      format: "dddd, MMMM Do YYYY, h:mm a"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
    views:  # 阅读次数
      enable: false
      source: "leancloud"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"
code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true
links:
  items:
    - {
      title: 'drawio画图工具',
      intro: 'drawio画图工具',
      link: 'https://aiden-coding.github.io/learn_drawio/',
      avatar: '/img/favicon.png'
    }
    - {
      title: '中文变量起名',
      intro: '中文变量起名',
      link: 'https://unbug.github.io/codelf/',
      avatar: '/img/favicon.png'
    }
  default_avatar: /img/avatar.png
web_analytics:  # 网页访问统计
  enable: true # 默认为false，启用网页统计改为true即可
  baidu:  # 百度统计的Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
  google:  # Google统计的Tracking ID，参见 https://analytics.google.com/analytics/web/
  tencent:  # 腾讯统计的H5 App id，参见 https://mta.qq.com/h5/manage/ctr_app_manage (开启高级功能才有cid)
    sid:
    cid:
  woyaola:  # 51.la站点统计ID，参见 https://www.51.la/user/site/index
  cnzz:  # 友盟/cnzz站点统计web_id，参见 https://web.umeng.com/main.php?c=site&a=show
  leancloud:  # LeanCloud 计数统计，可用于 PV UV 展示，如果 web_analytics.enable 没有开启，PV UV 展示只会查询，不会增加
    app_id:
    app_key:
    server_url:  # REST API 服务器地址，国际版不填

footer:
  statistics:
    enable: false
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

# 指定自定义 css 文件路径，路径是相对 source 目录
#custom_css:
#  - /css/bootstrap.min.css
#  - /css/font_1749284_hj8rtnfg7um.css
#  - /css/font_1736178_lbnruvf0jn.css
#  - /css/nprogress.min.css
#
#custom_js:
#  - /js/nprogress.min.js
#  - /js/jquery.min.js
#  - /js/bootstrap.min.js

